const ADD_PRODUCT = 'ADD_PRODUCT';
const REMOVE_PRODUCT = "REMOVE_PRODUCT";
const TOGGLE_STATUS_PRODUCT = "TOOGLE_STATUS_PRODUCT";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export default {ADD_PRODUCT,REMOVE_PRODUCT,TOGGLE_STATUS_PRODUCT,GET_ALL_PRODUCTS};